# Generated by Django 2.1.5 on 2019-02-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20190126_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='preceeded_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_chapter', to='stories.Story'),
        ),
    ]
