# Generated by Django 2.1.7 on 2019-02-22 18:15

from django.db import migrations
from django.template.defaultfilters import truncatechars

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Story = apps.get_model("stories", "Story")
    db_alias = schema_editor.connection.alias
    for story in Story.objects.using(db_alias).filter(published_at__isnull=False):
        # Evidently the turncate length is sort of a goal or a guideline, but not actually 
        story.teaser = truncatechars(story.text, Story._meta.get_field('teaser').max_length)
        story.save()

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Story = apps.get_model("stories", "Story")
    db_alias = schema_editor.connection.alias
    for story in Story.objects.using(db_alias).filter(published_at__isnull=False):
        story.teaser = None
        story.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20190222_1517'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
