# Generated by Django 2.1.7 on 2019-02-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_create_teaser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
    ]
