name: webapp
type: python:3.7

web:
  commands:
    start: "gunicorn -b $PORT ../gunicorn_diary.py"
  locations:
    "/":
      root: ""
      passthru: true
      allow: false
    "/static":
      root: "diary/site/static/"
      allow: true

hooks:
  build: |
    pip install --upgrade pip
    pip install -r dev.txt
    set -x
    DJANGO_SETTINGS_MODULE=diary.platform_test_settings python diary/manage.py test diary

  deploy: |
    set -x
    printenv
    python diary/manage.py collectstatic --no-input
    python diary/manage.py migrate

mounts:
   tmp:
       source: local
       source_path: tmp
   logs:
       source: local
       source_path: logs

disk: 512

relationships:
    database: "database:postgresql"
