language: python

dist: xenial

python:
  - 3.7
  
install:
  - pip install -r dev.txt

before_script:
  - psql -c 'create database diary_test;' -U postgres

script: DJANGO_SETTINGS_MODULE=diary.test_settings coverage run -a --branch diary/manage.py test

services:
  - postgresql
     
after_success: coveralls
