# Generated by Django 2.1.5 on 2019-01-24 15:53

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bio_text',
            field=martor.models.MartorField(blank=True),
        ),
    ]
