"https://{default}/":
  type: upstream
  upstream: "app:http"
"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
  
#tls:
#    strict_transport_security:
#        enabled: true
#        include_subdomains: true
#        preload: true
